name: Terraform Security Pipeline

on:
  pull_request:
    branches:
      - dev
      - staging
      - main

permissions:
  id-token: write
  contents: read

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1
        with:
          working_directory: infra/

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Run Trivy on Terraform Modules
        uses: aquasecurity/trivy-action@v0
        with:
          scan-type: fs
          scan-path: infra/
          exit-code: 1

      #- name: Send Email Alert on Failure
      #  if: failure()
      #  run: | 